CREATE TABLE cie10
(
    code VARCHAR(10)  NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_cie10 PRIMARY KEY (code)
);

CREATE TABLE consultation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date,
    type            VARCHAR(255),
    patient_id      BIGINT                                  NOT NULL,
    professional_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_consultation PRIMARY KEY (id)
);

CREATE TABLE diagnosis
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consultation_id BIGINT                                  NOT NULL,
    cie10_code      VARCHAR(10)                             NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT pk_diagnosis PRIMARY KEY (id)
);

CREATE TABLE healthcare_professional
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rut       VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    specialty VARCHAR(255),
    CONSTRAINT pk_healthcareprofessional PRIMARY KEY (id)
);

CREATE TABLE medication
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255)                            NOT NULL,
    pharmaceutical_form_id BIGINT,
    dosage                 VARCHAR(255),
    CONSTRAINT pk_medication PRIMARY KEY (id)
);

CREATE TABLE patient
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rut                VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    birth_date         date                                    NOT NULL,
    sex                VARCHAR(1),
    residential_sector VARCHAR(255),
    fonasa_tier        VARCHAR(255),
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

CREATE TABLE pharmaceutical_form
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_pharmaceuticalform PRIMARY KEY (id)
);

CREATE TABLE prescription
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date,
    consultation_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_prescription PRIMARY KEY (id)
);

CREATE TABLE prescription_medication
(
    quantity        INTEGER NOT NULL,
    instructions    VARCHAR(255),
    prescription_id BIGINT  NOT NULL,
    medication_id   BIGINT  NOT NULL,
    CONSTRAINT pk_prescriptionmedication PRIMARY KEY (prescription_id, medication_id)
);

ALTER TABLE healthcare_professional
    ADD CONSTRAINT uc_healthcareprofessional_rut UNIQUE (rut);

ALTER TABLE patient
    ADD CONSTRAINT uc_patient_rut UNIQUE (rut);

CREATE INDEX idx_consultation_patient_date ON consultation (patient_id, date);

CREATE INDEX idx_prescription_consultation_date ON prescription (consultation_id, date);

CREATE INDEX idx_professional_rut ON healthcare_professional (rut);

ALTER TABLE consultation
    ADD CONSTRAINT FK_CONSULTATION_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);

ALTER TABLE consultation
    ADD CONSTRAINT FK_CONSULTATION_ON_PROFESSIONAL FOREIGN KEY (professional_id) REFERENCES healthcare_professional (id);

ALTER TABLE diagnosis
    ADD CONSTRAINT FK_DIAGNOSIS_ON_CIE10_CODE FOREIGN KEY (cie10_code) REFERENCES cie10 (code);

CREATE INDEX idx_diagnosis_cie10 ON diagnosis (cie10_code);

ALTER TABLE diagnosis
    ADD CONSTRAINT FK_DIAGNOSIS_ON_CONSULTATION FOREIGN KEY (consultation_id) REFERENCES consultation (id);

ALTER TABLE medication
    ADD CONSTRAINT FK_MEDICATION_ON_PHARMACEUTICALFORM FOREIGN KEY (pharmaceutical_form_id) REFERENCES pharmaceutical_form (id);

ALTER TABLE prescription_medication
    ADD CONSTRAINT FK_PRESCRIPTIONMEDICATION_ON_MEDICATION FOREIGN KEY (medication_id) REFERENCES medication (id);

ALTER TABLE prescription_medication
    ADD CONSTRAINT FK_PRESCRIPTIONMEDICATION_ON_PRESCRIPTION FOREIGN KEY (prescription_id) REFERENCES prescription (id);

ALTER TABLE prescription
    ADD CONSTRAINT FK_PRESCRIPTION_ON_CONSULTATION FOREIGN KEY (consultation_id) REFERENCES consultation (id);