-- Create users table
CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255)                            NOT NULL,
    lastname  VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL UNIQUE,
    password  VARCHAR(255)                            NOT NULL,
    role      VARCHAR(50)                             NOT NULL,
    enabled   BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Create index on email for faster lookups
CREATE INDEX idx_users_email ON users (email);

